title: Heart Disease Prediction with Machine Learning
description: 2022 annual US Centers for Disease Control and Prevention (CDC) survey data of 400k+ adults related to their health status
show_downloads: 
google_analytics:
theme: jekyll-theme-cayman
